export default function ContentWithPotentialError() {
  throw new Error("Error occured in ContentWithPotentialError!")
}